### ISSUE TITLE
Problem with galleryHub integration

### ISSUE THREAD

**Issue by Tciferblatt** [lieszkol/november-gallery#2]
After installing november-gallery in my OctoberCMS project and adding few galleries, i'll try to integrate galleryHub to my Layout / Page / Partial and in all cases i get an error:

An exception has been thrown during the rendering of a template ("Partial '::default.htm' not found.").

/home/zzz/domains/zzzzz.eu/public_html/themes/zzzzzz/pages/zzzzzzz.htm line 28

Plug-in reinstalling had not resolved the problem ;(
My question about this in OctoberCMS site had not been answered.
Can you help me with this problem?

Event log:
#0[internal function]:Cms\Classes\Controller->renderPartial('::default.htm')
#1/home/zzzzz/domains/zzzzz.eu/public_html/modules/cms/classes/ComponentBase.php(143): call_user_func_array(Array, Array)
#2/home/zzzzz/domains/zzzzz.eu/public_html/plugins/zenware/novembergallery/components/GalleryHub.php(268): Cms\Classes\ComponentBase->renderPartial('@default.htm')
#3/home/zzzzz/domains/zzzzz.eu/public_html/modules/cms/classes/Controller.php(1213): ZenWare\NovemberGallery\Components\GalleryHub->onRender()
4/home/zzzzz/domains/zzzzz.eu/public_html/modules/cms/twig/Extension.php(124): Cms\Classes\Controller->renderComponent('galleryHub', Array)
#5/home/zzzzz/domains/zzzzz.eu/public_html/storage/cms/twig/03/034ea3542092ab9ee7e437bead66fd65a43eec28936e846463d3b7c4c4b6264b.php(87): Cms\Twig\Extension->componentFunction('galleryHub', Array)

Thank you in advance!

**Comment by lieszkol** [comment]
Hi Dmitrij,
I see that you wrote on the October support forum, email, and Gitter as well. Let's see if we can resolve your situation on Gitter/email, and we will post the result of our troubleshooting here once we have resolved your issue. Thanks!

**Comment by lieszkol** [comment]
Hi Dmitrij,

We discussed this over email. For anyone else having similar issues, please refer to [this page in the November Gallery cookbook](https://its.zensoft.hu/books/november-gallery-cookbook/page/adding-a-gallery-to-a-theme-with-%22blocks%22)

I am closing this issue. If you have further questions please write to me on Gitter again! Thanks.
