### ISSUE TITLE
Feature request - additional field for filtering

### ISSUE THREAD

**Issue by snoopy21** [lieszkol/november-gallery#3]
It would be handy to have an additional field for each attachement, so you have the possibility to restrict access on selected images but not the whole gallery.

**Comment by lieszkol** [comment]
Hi Snoopy,
Just seeing this issue. Are you still using the plugin? Please elaborate how you would imagine this to work. Would the filtering filter by filename?

**Comment by lieszkol** [comment]
Closing this issue until there is further interest.
